### ISSUE TITLE
Implement Event Searching

### ISSUE THREAD

**Issue by DootLord** [HarryW96/INSE_Development#11]
Events should be searchable by users

Likely by storing events in their own database, and then having a search through the table server-side and then display the event that searches the name of the event

**Comment by DootLord** [comment]
Events will likely be populated from the first five (or how many we decide on later) results from the SQL query, using details from the rows of the database to populate each list element.

On clicking an element, the event will redirect to the event page that will be filled with data from the row in question. From there the user can buy tickets and interact with the event as normal.

**Comment by DootLord** [comment]
I'll take on the restful part of the function.
Harry I'm assuming you're alright with the front end?

**Comment by HarryW96** [comment]
Event searching is working!
