### ISSUE TITLE
Searching for nothing lists first events in the database.

### ISSUE THREAD

**Issue by HarryW96** [HarryW96/INSE_Development#16]
Could be an issue with the SQL query? The majority of people will not be searching for a null so can be marked as low priority for now if that's okay?

**Comment by DootLord** [comment]
I think the "LIKE" command just trys its best with nothing and returns whatever it can.

I think we can get around this by doing a quick check on the box to ensure it's not empty first. 👍

**Comment by HarryW96** [comment]
I will have a look into it!

**Comment by HarryW96** [comment]
fixed by not allowing empty searching
