### ISSUE TITLE
Naked Branch: Sidebar on first page doesn't work. Fades the screen.

### ISSUE THREAD

**Issue by DootLord** [HarryW96/INSE_Development#4]
Side bar no longer works on the first page of the website. Instead just fades the screen. I assume the scope of the bar no longer works properly. 

Should be easy fix, I'm just not comfortable with the zurb framework.

**Comment by HarryW96** [comment]
Merge seemed to have caused some issues with zurb trying to implement its own head rather than our one we wrote. This is what was causing issue with the menus, now been fixed and all seems to be working correctly.
