### ISSUE TITLE
Add event implementation

### ISSUE THREAD

**Issue by DootLord** [HarryW96/INSE_Development#9]
Events will need to be created, likely with a automatic google form or a custom page.

1) Way to show off events
2) Event Generation

**Comment by DootLord** [comment]
There was talk about having clients talk to us via email or personally to create their own events, instead of using an automated solution, is this the case?

**Comment by HarryW96** [comment]
I believe this was the case so all event creation would be handled from our end. This was due to time restraints and having to implement a system that will handle it. We can keep this open but have it as low priority and only implement if we were to have time?

**Comment by DootLord** [comment]
That's fine then, we'll drop this issue as this is what we've mentioned in our design document I believe.
